[package]
name = "index-bloom"
version = "0.1.0"
authors = ["Olivier Despesse <olived19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
unidecode = "0.3.0"
